=== jdpro/cubes_app/data/agregats.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.dornbusch.fr/2012/cubes" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" 	xmlns="http://www.dornbusch.fr/2012/cubes">

    <element name="agregat" type="Agregat"></element>
    
    <complexType name="Agregat">
    	<sequence>
    		<element name="composante" type="Agregat"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    	</sequence>
    	<attribute name="id" type="string" use="required"></attribute>
    	<attribute name="libelle" type="string"></attribute>
    	<attribute name="definition" type="string" use="optional"></attribute>
    	<attribute name="article" type="string" use="required"></attribute>
    	<attribute name="majuscule_obligatoire" type="boolean" use="optional"></attribute>
    </complexType>

</schema>

=== jdpro/cubes_app/data/popact.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="affichage-donnees.xsl" type="text/xsl"?>
<agregat xmlns="http://www.dornbusch.fr/2012/cubes"
	xsi:schemaLocation="agregats.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	article="la" id="PT" libelle="population totale" definition="Ensemble de la population recensée sur un territoire donné à une date donnée.">
	<composante article="les" id="RET" libelle="retraités"
		definition="Ensemble des personnes qui se sont retirées la vie professionnelles. Inactifs qui ne sont plus le plus souvent en âge de travailler.">
	</composante>
	<composante article="les" id="ID" libelle="inactifs divers"
		definition="Inactifs en âge de travailler mais ayant fait le choix (pères ou mères au foyer), ne pouvant pas travailler (handicap, longue maladie…) ou ne parvenant pas à trouver un emploi (chômeurs découragés recensés comme inactifs).">
	</composante>
	<composante article="les" libelle="scolaires, étudiants" id="SE"
		definition="Inactifs n’ayant pas l’âge de travailler (élèves de moins de 15 ans) ou ayant choisi de poursuivre leurs études (étudiants de plus de 15 ans).">
	</composante>
	<composante article="la" libelle="population active" id="PA"
		definition="Ensemble des personnes en âge de travailler qui occupent un emploi ou en cherchent un.">
		<composante article="les" id="PAI" libelle="Chômeurs"
			definition="Actif sans emploi qui, selon la définition internationale adoptée par le BIT, est une personne sans emploi, qui en recherche un de façon active et qui est immédiatement disponible.">
		</composante>
		<composante article="la" libelle="population active occupée"
			id="PAO" definition="Actif occupant un emploi salarié ou indépendant.">
			<composante id="IND" article="les"
				libelle="indépendants" definition="Actifs occupés exerçant une activité non-salariée, à caractère artisanal, commercial ou libéral. Contrairement aux salariés ils organisent leur travail librement, en dehors de tout lien de subordination. ">
			</composante>
			<composante article="les" id="SAL" libelle="salariés"
				definition="Actifs occupés qui s’engagent pour une période (limitée ou indéterminée), à exécuter un travail, à temps plein ou à temps partiel pour le compte d’un employeur, en contrepartie d’un salaire ou d’un traitement. Les conditions de la subordination à l’employeur sont le plus souvent décrites dans le contrat de travail qui le lie à son entreprise.">
				<composante id="FON" article="les"
					libelle="fonctionnaires" definition="Salariés dont l’employeur est une administration publique.">
				</composante>
				<composante id="SDP" article="les"
					libelle="salariés de droit privé" definition="Salarié dont la subordination à un employeur est établie par un contrat de travail relevant du droit privé.">
				</composante>
			</composante>
		</composante>
	</composante>
</agregat>

=== jdpro/cubes_app/data/massemon.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="affichage-donnees.xsl" type="text/xsl"?>
<agregat xmlns="http://www.dornbusch.fr/2012/cubes"
	xsi:schemaLocation="agregats.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	libelle="Actifs mobiliers" article="les" id="AM" definition="">
	<composante libelle="Actifs non monétaires" article="les"
		id="ANM"
		definition="Titres ne pouvant être convertis rapidement en moyens de paiement, tels que les actions ou les obligations.">
	</composante>
	<composante libelle="M3" article="" id="M3"
		majuscule_obligatoire="true"
		definition="M3 égale M2 plus divers placements monétaires émis par les institutions financières négociables sur le marché monétaire. Il s’agit d’actifs dont le degré de liquidité est faible, essentiellement des dépôts à terme d'une durée inférieure à 2 ans, et des OPCVM monétaires. L'agrégat M3 est l'indicateur le plus large concernant le crédit bancaire, mais non pas l'ensemble du crédit dont une partie passe directement par les marchés financiers.">
		<composante libelle="Titres d'OPCVM monétaires" article="les"
			id="SM"
			definition="Un OPCVM, ou Organisme de Placement Collectif en Valeurs Mobilières, est une entité qui gère un portefeuille dont les fonds investis sont placés en valeurs mobilières (actions ou obligations en particulier).">
		</composante>
		<composante libelle="Certificats de dépôt" article="les"
			id="DD"
			definition="Ce sont des instruments du marché monétaire, c’est-à-dire des titres d’une durée inférieure ou égale à un an négociables sur le marché monétaire.">
		</composante>
		<composante article="" libelle="M2" id="M2"
			majuscule_obligatoire="true"
			definition='M2 est égal à M1 plus le "crédit à court terme" à savoir les dépôts à terme inférieurs ou égaux à deux ans assortis d’un préavis de remboursement inférieur ou égal à trois mois. Le crédit à cours terme concerne ainsi principalement les comptes sur livrets qui peuvent être convertis aisément en actifs plus liquides.'>
			<composante libelle="comptes sur livrets" article="les"
				id="CL"
				definition="Il s’agit des dépôts avec un préavis inférieur ou égal à 3 mois (livrets A, CODEVI, comptes épargne logement, livrets d’épargne populaire, livrets jeunes…)">
			</composante>
			<composante libelle="M1" article="" id="M1"
				majuscule_obligatoire="true"
				definition="L'agrégat M1, regroupe le total des pièces et billets en circulation et des dépôts bancaires à vue (comptes courants).">
				<composante libelle="Monnaie scripturale" article="la"
					id="MS"
					definition="Dépôts monétaires dans les banques, dits « comptes à vue » (non rémunérés), sur lesquels il est possible d’effectuer des retraits, des virements par chèque ou carte bancaire. ">
				</composante>
				<composante definition="Billets et pièces (monnaie divisionnaire)"
					article="la" libelle="Monnaie fiduciaire" id="MF">
				</composante>
			</composante>
		</composante>
		<composante article="les" id="PE"
			definition="Ce sont des espèces perçues en contrepartie de titres vendus aux institutions financières  à un prix donné avec engagement de rachat à un prix et à une date donnés."
			libelle="pensions" majuscule_obligatoire="true">
		</composante>
	</composante>
</agregat>

=== jdpro/cubes_app/data/vab.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="affichage-donnees.xsl" type="text/xsl"?>
<agregat id="CA" libelle="Chiffre d'affaires" xmlns="http://www.dornbusch.fr/2012/cubes"
	xsi:schemaLocation="agregats.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	article="le"
	definition="Montant de la production vendue par l'entreprise (recette totale).">
	<composante id="CI" libelle="Consommations intermédiaires"
		article="les"
		definition="Moyens de production détruits ou transformés au cours du cycle de production et dont la durée de vie est de moins d'un an.">
	</composante>
	<composante id="VA" libelle="Valeur ajoutée" article="la"
		definition="Richesse nouvelle créée au cours du processus de production : valeur de la production finale de biens et/ou services moins valeur des consommations intermédiaires utilisées pour les produire.">
		<composante id="RS" libelle="Rémunération des salariés"
			article="la"
			definition="Ensemble des salaires directs et des cotisations sociales versées aux salariés en contrepartie de leur travail. ">
		</composante>
		<composante id="IP" libelle="Impôts sur la production"
			article="les"
			definition="Impôts que les entreprises supportent du fait de leurs activités de production : taxe professionnelle, taxe foncière...">
		</composante>
		<composante id="EBE" libelle="Excédent brut d'exploitation"
			article="l'"
			definition="Désigne ce qu’il reste de la valeur ajoutée, déduction faite des salaires, des cotisations sociales et des impôts sur la production. Il s’agit d’une mesure des profits au sens large.">
			<composante article="l'" id="AM" libelle="Amortissement"
				definition="Mesure comptable de la perte de valeur du capital fixe due à l'usure ou à l'obsolescence. ">
			</composante>
			<composante id="INTV" libelle="Intérêts versés" article="les"
				definition="Loyers versés par l'entreprise qui utilise des fonds empruntés afin de rémunérer ses créanciers.">
			</composante>
			<composante id="RE" libelle="Résultat d'exploitation"
				article="le"
				definition="Différence entre les charges et les produits d'exploitation : s'obtient en retranchant de l'EBE le montant des amortissements et les intérêts versés aux prêteurs.">
				<composante id="IS" libelle="Impôt sur les sociétés"
					article="l'" definition="Impôt perçu sur les bénéfices des sociétés.">
				</composante>
				<composante id="BN" libelle="Bénéfice net" article="le"
					definition="Bénéfice qui revient à l'entreprise après paiement de l'impôt sur les sociétés.">
					<composante id="BC" libelle="Bénéfice conservé par l'entreprise"
						article="le"
						definition="Part du bénéfice net non distribué aux propriétaires ou actionnaires.">
					</composante>
					<composante id="DIV" libelle="Dividendes" article="les"
						definition="Part du bénéfice net distribuée aux actionnaires.">
					</composante>
				</composante>
			</composante>
		</composante>
	</composante>

</agregat>
